In [18]:
import pandas as pd

df = pd.read_csv('../data/exportacao_full.csv')

display(df)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2010,1,Afghanistan,Itajaí - SC,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),197162,99945
1,2010,1,Afghanistan,Lapa - PR,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),114570,76989
2,2010,1,Afghanistan,Rolândia - PR,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),72900,54000
3,2010,1,Afghanistan,São Paulo - SP,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),153593,106541
4,2010,1,Afghanistan,Xaxim - SC,207,"Meat and edible offal, of the poultry of headi...",2,Meat and edible meat offal,Asia (minus MIDDLE EAST),26739,24990
...,...,...,...,...,...,...,...,...,...,...,...
13124808,2013,10,Nigeria,Barueri - SP,8414,"Air or vacuum pumps, air or other gas compress...",84,"Nuclear reactors, boilers, machinery and mecha...",Africa (minus MIDDLE EAST),112,3
13124809,2013,10,Nigeria,Barueri - SP,8421,"Centrifuges, including centrifugal dryers; fil...",84,"Nuclear reactors, boilers, machinery and mecha...",Africa (minus MIDDLE EAST),34,1
13124810,2013,10,Nigeria,Barueri - SP,8482,Ball or roller bearings,84,"Nuclear reactors, boilers, machinery and mecha...",Africa (minus MIDDLE EAST),57,0
13124811,2013,10,Nigeria,Barueri - SP,8512,Electrical lighting or signalling equipment (e...,85,Electrical machinery and equipment and parts t...,Africa (minus MIDDLE EAST),23,1
13124812,2013,10,Nigeria,Barueri - SP,8708,Parts and accessories of the motor vehicles of...,87,Vehicles other than railway or tramway rolling...,Africa (minus MIDDLE EAST),1292,49